modules = {
    core {
        dependsOn 'jquery','css','javascriptlib','controller'
    }

	css {
		resource url:'/fonts/themify-icons/themify-icons.css'
		resource url:'/fonts/weather-icons/css/weather-icons.css'
		 resource url:'/css/lib/bootstrap.css'
		 resource url:'/css/lib/ui.css'
		 resource url:'/css/lib/loading-bar.css'
		 resource url:'/css/lib/angular-ui-notification.min.css'
		 resource url:'/css/lib/main.css'
		 resource url:'/css/lib/chosen-bootstrap.css'	 
		 resource url:'/css/lib/chosen.css'
		 resource url:'/css/lib/animations.css'
		 resource url:'/css/lib/toaster.css'
		 resource url:'/css/lib/ng-table.min.css'
		 resource url:'/css/custom/common.css'
		 resource url:'/css/custom/custom.css'
		 resource url:'/css/custom/style.css'
		
		
		 
	}
	
	javascriptlib {

//		resource url:'http://code.angularjs.org/1.2.23/angular.min.js'
//		resource url:'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'
//		resource url:'http://code.angularjs.org/1.2.23/angular-animate.min.js'
//		resource url:'http://code.angularjs.org/1.2.23/angular-sanitize.min.js'
//		resource url:'http://code.angularjs.org/1.2.23/angular-route.min.js'	
		resource url:'/js/lib/angular/angular.min.js'
		resource url:'js/directives/bootstrap.min.js'
		resource url:'/js/lib/angular-route/angular-route.min.js'
		resource url:'/js/lib/angular-animate/angular-animate.min.js'
		resource url:'/js/lib/angular-sanitize/angular-sanitize.min.js'
		resource url:'/js/lib/angular-cookies/angular-cookies.min.js'
		resource url:'/js/lib/underscore/underscore-min.js'
		resource url:'/js/lib/restangular/restangular.min.js'
		resource url:'/js/lib/angular-bootstrap/ui-bootstrap-tpls.min.js'
		resource url:'/js/lib/jquery-spinner/dist/jquery.spinner.min.js'
		resource url:'/js/lib/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js'
		resource url:'/js/lib/bootstrap-file-input/bootstrap.file-input.js'
		resource url:'/js/lib/jquery-steps/build/jquery.steps.min.js'
		resource url:'/js/lib/jquery.slimscroll/jquery.slimscroll.min.js'
		resource url:'/js/lib/vendors/jquery.sparkline.min.js'
		resource url:'/js/lib/flot/jquery.flot.js'
		resource url:'/js/lib/flot/jquery.flot.resize.js'
		resource url:'/js/lib/flot/jquery.flot.pie.js'
		resource  url:'/js/lib/flot/jquery.flot.categories.js'
		resource url:'/js/lib/vendors/jquery.flot.orderBars.js'
		resource url:'/js/lib/flot/jquery.flot.stack.js'
		resource url:'/js/lib/flot.curvedlines/curvedLines.js'
		resource url:'/js/lib/flot.tooltip/js/jquery.flot.tooltip.min.js'
		resource url:'/js/lib/flot/jquery.flot.time.js'
		resource url:'/js/lib/flot/jquery.flot.tickrotor.js'
		resource url:'/js/lib/jquery.easy-pie-chart/dist/angular.easypiechart.min.js'
		resource url:'/js/lib/angular-ui-tree/dist/angular-ui-tree.min.js'
		resource url:'/js/lib/ngmap/build/scripts/ng-map.min.js'
		resource url:'/js/lib/ng-tags-input/ng-tags-input.min.js'
		resource url:'/js/lib/vendors/jquery-jvectormap-1.2.2.min.js'
		resource url:'/js/lib/vendors/jquery-jvectormap-world-mill-en.js'
		resource url:'/js/lib/ngAutocomplete/ngAutocomplete.js'
		resource url:'/js/lib/moment.min.js'
		
		}
	controller {
		resource url:'/js/conf/app.js'
		resource url:'/js/directives/angular-validation.js'
		resource url:'/js/directives/angular-ui-notification.min.js'
		resource url:'/js/directives/angular-cookie.js'
		resource url:'/js/directives/ng-environments.min.js'
		resource url:'/js/directives/angular-file-upload.min.js'
		resource url:'/js/directives/angular-strap.js'
		resource url:'/js/directives/angular-strap.tpl.js'
		resource url:'/js/directives/toaster.js'
		resource url:'/js/lib/angular-chosen/chosen.js'
		resource url:'/js/lib/angular-chosen/chosen.jquery.js'
		resource url:'/js/directives/ng-table.min.js'
		resource url:'/js/directives/loading-bar.js'	
		resource url:'/js/directives/angular-busy.js'
		resource url:'/js/conf/config.js'
		resource url:'/js/conf/constant.js'
		resource url:'/js/directives/custom.js'
		resource url:'/js/services/custom.js'
		resource url:'/js/conf/route.js'
		resource url:'/js/controllers/shared/main.js'
		resource url:'/js/controllers/shared/directives.js'
		resource url:'/js/controllers/shared/localize.js'
		resource url:'/js/controllers/shared/Nav.js'
		resource url:'/js/controllers/UI/UICtrl.js'
		resource url:'/js/controllers/UI/UIDirective.js'
		resource url:'/js/controllers/UI/UIService.js'
		resource url:'/js/controllers/UI/Map.js'
		resource url:'/js/controllers/Form/FormDirective.js'
		resource url:'/js/controllers/Form/FormCtrl.js'
		resource url:'/js/controllers/Form/FormValidation.js'
		resource url:'/js/controllers/Table/TableCtrl.js'
		resource url:'/js/controllers/Task/Task.js'
		resource url:'/js/controllers/Chart/ChartCtrl.js'
		resource url:'/js/controllers/Chart/ChartDirective.js'
		resource url:'/js/controllers/Page/PageCtrl.js'
		resource url:'/js/controllers/HomeCtrl.js'
		resource url:'/js/controllers/LoginCtrl.js'
		resource url:'/js/controllers/SurveyCtrl.js'
		resource url:'/js/controllers/SurveyformCtrl.js'
		resource url:'/js/controllers/DashboardCtrl.js'
		resource url:'/js/controllers/UserCtrl.js'
		resource url:'/js/controllers/SurveydetailsCtrl.js'
		resource url:'/js/controllers/UserProfileCtrl.js'
		resource url:'/js/controllers/ForgetpwdCtrl.js'
		resource url:'/js/controllers/ResetpwdCtrl.js'
		resource url:'/js/controllers/QuestionCtrl.js'
		resource url:'/js/controllers/SurveychartdetailsCtrl.js'
		resource url:'/js/controllers/CommentsCtrl.js'
		resource url:'/js/controllers/GiftCtrl.js'
		resource url:'/js/controllers/UserProfileSurveysCtrl.js'
		

	}

}